name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install npm dependencies
      run: npm ci
    - name: Run Tests (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test
    - name: Run Tests (MacOS, Windows)
      if: runner.os != 'Linux'
      run: npm test
    - name: Package extension
      if: runner.os == 'Linux'
      run: npm run vscode:package
    - name: Upload extension
      uses: actions/upload-artifact@v3
      if: runner.os == 'Linux'
      with:
        name: vscode-apex-pmd
        path: apex-pmd-*.vsix
