name: Update PMD

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        persist-credentials: true
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install npm dependencies
      run: npm ci
    - name: Update PMD
      id: pmd
      shell: bash
      run: |
        VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | jq --raw-output ".tag_name" | sed 's:.*/::')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        cd pmd-packager
        ./upgrade.sh "$VERSION"
    - name: Commit and Push
      shell: bash
      run: |
        # configure git
        # see https://github.com/orgs/community/discussions/26560 and https://api.github.com/users/github-actions[bot]
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Update PMD ${{ steps.pmd.version }}"
    - name: Run Tests
      shell: bash
      run: npm test
    - name: Push
      shell: bash
      run: |
        git push origin

# TODO: Update CHANGELOG.md
# TODO: Create a PR instead?
