name: Update PMD

#
# - Updates PMD to the latest released version of PMD.
# - Runs the tests
# - Creates a new pull request for the changes
#

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        persist-credentials: true
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install npm dependencies
      run: npm ci
    - name: Upgrade PMD
      id: pmd
      shell: bash
      run: |
        PMD_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | jq --raw-output ".tag_name" | sed 's:.*/::')
        echo "version=$PMD_VERSION" >> $GITHUB_OUTPUT
        cd pmd-packager
        ./upgrade.sh "$PMD_VERSION"
    - name: Update CHANGELOG
      shell: bash
      run: |
        LINE=$(grep -n "^## \[Unreleased\]" CHANGELOG.md | cut -d ':' -f 1)
        BEFORE=$(head -n $LINE CHANGELOG.md)
        AFTER=$(tail -n +$((LINE + 1)) CHANGELOG.md)
        {
          echo "$BEFORE"
          echo
          echo "* Upgraded to PMD ${PMD_VERSION}"
          echo "$AFTER"
        } > CHANGELOG.md
      env:
        PMD_VERSION: ${{ steps.pmd.version }}
    - name: Run Tests
      shell: bash
      run: npm test
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: Upgrade to PMD ${{ steps.pmd.version }}
        commit-message: Upgrade to PMD ${{ steps.pmd.version }}
        branch: upgrade-pmd-${{ steps.pmd.version }}
